server:
  port: 8082

spring:
  application:
    name: upload-file
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1901/eureka/


aliyun:
  endpoint:
  accessKeyId: 
  accessKeySecret: 
  bucketName: 
  urlPrefix: 