server:
  port: 5001
spring:
  application:
    name: data-center
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  #jpa setting
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 0
        max-wait: -1ms

  #阿里数据库连接池设置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://192.168.89.1:3306/thumbing?serverTimezone=Asia/Shanghai}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    druid:
      #最大值
      max-active: 100
      #最小值
      min-idle: 5
      #初始化大小
      initial-size: 5
      #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 6000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache
      pool-prepared-statements: true
      #最大PSCache连接
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      #'wall'用于防火墙
      filter:
        slf4j:
          statement-sql-pretty-format: true
          result-set-log-enabled: false
          statement-executable-sql-log-enable: false
          enabled: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      test-while-idle: true

  rabbitmq:
    username: guest
    password: guest
    addresses: 192.168.89.1:5672
    virtual-host: /
    listener:
      simple:
        concurrency: 5
        acknowledge-mode: manual
        max-concurrency: 10
        prefetch: 1
      direct:
        acknowledge-mode: manual
        prefetch: 1
  data:
    mongodb:
      host: 192.168.89.1
      port: 27017
      database: thumbing

eureka:
  client:
    #设置服务注册中心的URL
    service-url:
      defaultZone: http://localhost:1901/eureka/

push-data:
  data-center:
    port: 4001
    messagePort: 4011
    devicePort: 0
    name: center1
    initializedConnect: 16384
  zookeeper:
    servers: localhost:2181,localhost:2182,localhost:2183
    namespace: thumbing
    session-timeout: 6000
    connection-timeout: 6000
    max-retries: 1000
    retries-sleep-time: 2000
use:
  redis: true
  security: true
  feign: true
  swagger: true
  customThreadPool: false
  rabbitmq: true

security:
  ignores: /error/**;/swagger-resources/**;/swagger-ui.html;/v2/api-docs;/webjars/**

feign:
  client:
    config:
      default:
        connectTimeout: 5000   #连接超时3秒，连接失败时直接调用降级方法
        readTimeout: 100000     #连接成功，处理数据的时间限制10秒 100000   读取时间过短会抛异常java.net.SocketTimeoutException: Read timed out
        loggerLevel: full      #日志输出等级
  hystrix:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  #服务连接成功，但是时间过长，降级方法调用时间   60000   5000

authentication:
  expirationTime: 3600 # Number of minutes
  issuer: thumbing
  signingKey: xm8EV6Hy5RMFK4EEACIDAwQus48djvcnjsdksfksjdfwiuersdkjhfskjdhfskjdf

thread:
  pool:
    busy: true
    maxUtilization: 1
    maxWaitingTasksPerThread: 40
    maxExtraThreads: 5
    maxIdleSeconds: 60
    threadName: dataCenterHandler
    rejectedExecutionHandlerClassName: com.thumbing.shared.thread.RejectHandler