server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: data
          uri: lb://data-center
          predicates:
            - Path=/api/data/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=2
eureka:
  client:
    #设置服务注册中心的URL
    service-url:
      defaultZone: http://localhost:1901/eureka/
