server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: data
          uri: lb://data-center
          predicates:
            - Path=/api/data/**
          filters:
            - StripPrefix=2
        - id: file
          uri: lb://upload-file
          predicates:
            - Path=/api/file/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1901/eureka/
