server:
  port: 8081

spring:
  application:
    name: gateway
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 0
        max-wait: -1ms

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: data
          uri: lb://data-center
          predicates:
            - Path=/api/data/**
          filters:
            - StripPrefix=2
        - id: file
          uri: lb://upload-file
          predicates:
            - Path=/api/file/**
          filters:
            - StripPrefix=2
        - id: auth
          uri: lb://auth-server
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: content
          uri: lb://content-server
          predicates:
            - Path=/api/content/**
          filters:
            - StripPrefix=2
        - id: user
          uri: lb://user-management
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
        - id: record
          uri: lb://record-server
          predicates:
            - Path=/api/record/**
          filters:
            - StripPrefix=2
        - id: content
          uri: lb://content-server
          predicates:
            - Path=/api/record/**
          filters:
            - StripPrefix=2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1901/eureka/
use:
  redis: false
  security: false
  feign: true
  swagger: false
  customThreadPool: false
  rabbitmq: false

security:
  ignores: /error/**;/swagger-resources/**;/swagger-ui.html;/v2/api-docs;/webjars/**

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 100000
        loggerLevel: full
  hystrix:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000