server:
  port: 7066
spring:
  application:
    name: content-server
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 0
        max-wait: -1ms
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  data:
    mongodb:
      host: 192.168.89.1
      port: 27017
      database: thumbing

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1901/eureka/

use:
  redis: true
  security: true
  feign: true
  swagger: true
  customThreadPool: false
  rabbitmq: false

security:
  ignores: /error/**;/swagger-resources/**;/swagger-ui.html;/v2/api-docs;/webjars/**

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 100000
        loggerLevel: full
  hystrix:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

authentication:
  expirationTime: 3600 # Number of minutes
  issuer: thumbing
  signingKey: xm8EV6Hy5RMFK4EEACIDAwQus48djvcnjsdksfksjdfwiuersdkjhfskjdhfskjdf

elasticsearch:
  host: 127.0.0.1, 127.0.0.1, 127.0.0.1
  port: 9201, 9202, 9203
  clusterName: thumbing
  schema: http
  index:
    name: doc
    shardNum: 3
    replicasNum: 2
    properties:
      -id
      -name
      -title
      -tags
      -content
      -date
      -userId
      -nickName
      -contentId

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:7070/xxl-job-admin
    accessToken:
    executor:
      appname: content-executor
      #注册地址[选填]，优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址
      address:
      #执行器IP[选填]，为空则自动获取
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30