server:
  port: 7066
spring:
  application:
    name: content-server
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 0
        max-wait: -1ms
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  rabbitmq:
    username: guest
    password: guest
    addresses: 192.168.89.1:5672
    virtual-host: /
    listener:
      simple:
        concurrency: 5
        acknowledge-mode: manual
        max-concurrency: 10
        prefetch: 1
      direct:
        acknowledge-mode: manual
        prefetch: 1
    data:
      mongodb:
        host: 192.168.89.1
        port: 27017
        database: thumbing

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1901/eureka/

use:
  redis: true
  security: true
  feign: true
  swagger: true

security:
  ignores: /error/**;/swagger-resources/**;/swagger-ui.html;/v2/api-docs;/webjars/**

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 100000
        loggerLevel: full
  hystrix:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
