server:
  port: 7001

spring:
  application:
    name: node-server
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  rabbitmq:
    addresses: 192.168.89.1:5672
    username: guest
    password: guest
    virtual-host: /
    publisher-returns: true
    publisher-confirm-type: correlated
push-data:
  node-server:
    port: 6001
    messagePort: 4021
    devicePort: 4031
    name: server1
    initializedConnect: 16384
  zookeeper:
    servers: localhost:2181,localhost:2182,localhost:2183
    namespace: thumbing
    session-timeout: 6000
    connection-timeout: 6000
    max-retries: 1000
    retries-sleep-time: 2000
use:
  redis: false
  security: false
  feign: false
  swagger: false
  customThreadPool: false
  rabbitmq: true