server:
  port: 7001

spring:
  application:
    name: node-server
  rabbitmq:
    addresses: localhost:5672
    username: root
    password: root
    virtual-host: /
    publisher-returns: true
    publisher-confirm-type: correlated
push-data:
  node-server:
    port: 9001
    messagePort: 8001
    devicePort: 3001
    name: NodeServer-1
    initializedConnect: 16384
  zookeeper:
    servers: localhost:2181,localhost:2182,localhost:2183
    listen-namespace: namespace-data-center
    namespace: namespace-node-server
    session-timeout: 6000
    connection-timeout: 6000
    max-retries: 1000
    retries-sleep-time: 2000
