server:
  port: 7001

spring:
  application:
    name: node-server
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    virtual-host: /
    publisher-returns: true
    publisher-confirm-type: correlated
  #阿里数据库连接池设置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://192.168.89.1:3306/mysql_loserclub}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    druid:
      #最大值
      max-active: 10
      #最小值
      min-idle: 5
      #初始化大小
      initial-size: 5
      #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 3000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache
      pool-prepared-statements: true
      #最大PSCache连接
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      #'wall'用于防火墙
      filter:
        slf4j:
          statement-sql-pretty-format: true
          result-set-log-enabled: false
          statement-executable-sql-log-enable: false
          enabled: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
push-data:
  node-server:
    port: 9001
    messagePort: 8001
    devicePort: 3001
    name: server1
    initializedConnect: 16384
  zookeeper:
    servers: localhost:2181,localhost:2182,localhost:2183
    namespace: loser-club
    session-timeout: 6000
    connection-timeout: 6000
    max-retries: 1000
    retries-sleep-time: 2000
